version: '3.8'

services:

    nginx:
        build:
            context: ./nginx
        container_name: nginx
        ports:
            - "8080:80"
        depends_on:
            - node
            - db
        networks:
            - node-network

    node:
        build:
            context: ./node
        container_name: node
        entrypoint: dockerize -wait tcp://db:3306 -timeout 30s sh -c "npm install && node index.js"
        tty: true
        depends_on:
            - db
        volumes:
            - ./node:/usr/src/app
        networks:
            - node-network

    db:
        image: mysql:5.7
        container_name: db
        restart: always
        tty: true
        environment:
            MYSQL_DATABASE: desafio02
            MYSQL_ROOT_PASSWORD: root
        ports:
            - "3306:3306"
        volumes:
            - ./db:/var/lib/mysql
        networks:
            - node-network

networks:
    node-network:
        driver: bridge
